/// Surah / juz metadata from Tanzil's quran-data.xml
/// (https://tanzil.net/docs/quran_metadata — (C) Tanzil.info, CC BY 3.0).
library;

const surahData = <(String, int, bool, String)>[
  ('الفاتحة', 7, true, "Al-Faatiha"),
  ('البقرة', 286, false, "Al-Baqara"),
  ('آل عمران', 200, false, "Aal-i-Imraan"),
  ('النساء', 176, false, "An-Nisaa"),
  ('المائدة', 120, false, "Al-Maaida"),
  ('الأنعام', 165, true, "Al-An'aam"),
  ('الأعراف', 206, true, "Al-A'raaf"),
  ('الأنفال', 75, false, "Al-Anfaal"),
  ('التوبة', 129, false, "At-Tawba"),
  ('يونس', 109, true, "Yunus"),
  ('هود', 123, true, "Hud"),
  ('يوسف', 111, true, "Yusuf"),
  ('الرعد', 43, false, "Ar-Ra'd"),
  ('ابراهيم', 52, true, "Ibrahim"),
  ('الحجر', 99, true, "Al-Hijr"),
  ('النحل', 128, true, "An-Nahl"),
  ('الإسراء', 111, true, "Al-Israa"),
  ('الكهف', 110, true, "Al-Kahf"),
  ('مريم', 98, true, "Maryam"),
  ('طه', 135, true, "Taa-Haa"),
  ('الأنبياء', 112, true, "Al-Anbiyaa"),
  ('الحج', 78, false, "Al-Hajj"),
  ('المؤمنون', 118, true, "Al-Muminoon"),
  ('النور', 64, false, "An-Noor"),
  ('الفرقان', 77, true, "Al-Furqaan"),
  ('الشعراء', 227, true, "Ash-Shu'araa"),
  ('النمل', 93, true, "An-Naml"),
  ('القصص', 88, true, "Al-Qasas"),
  ('العنكبوت', 69, true, "Al-Ankaboot"),
  ('الروم', 60, true, "Ar-Room"),
  ('لقمان', 34, true, "Luqman"),
  ('السجدة', 30, true, "As-Sajda"),
  ('الأحزاب', 73, false, "Al-Ahzaab"),
  ('سبإ', 54, true, "Saba"),
  ('فاطر', 45, true, "Faatir"),
  ('يس', 83, true, "Yaseen"),
  ('الصافات', 182, true, "As-Saaffaat"),
  ('ص', 88, true, "Saad"),
  ('الزمر', 75, true, "Az-Zumar"),
  ('غافر', 85, true, "Al-Ghaafir"),
  ('فصلت', 54, true, "Fussilat"),
  ('الشورى', 53, true, "Ash-Shura"),
  ('الزخرف', 89, true, "Az-Zukhruf"),
  ('الدخان', 59, true, "Ad-Dukhaan"),
  ('الجاثية', 37, true, "Al-Jaathiya"),
  ('الأحقاف', 35, true, "Al-Ahqaf"),
  ('محمد', 38, false, "Muhammad"),
  ('الفتح', 29, false, "Al-Fath"),
  ('الحجرات', 18, false, "Al-Hujuraat"),
  ('ق', 45, true, "Qaaf"),
  ('الذاريات', 60, true, "Adh-Dhaariyat"),
  ('الطور', 49, true, "At-Tur"),
  ('النجم', 62, true, "An-Najm"),
  ('القمر', 55, true, "Al-Qamar"),
  ('الرحمن', 78, false, "Ar-Rahmaan"),
  ('الواقعة', 96, true, "Al-Waaqia"),
  ('الحديد', 29, false, "Al-Hadid"),
  ('المجادلة', 22, false, "Al-Mujaadila"),
  ('الحشر', 24, false, "Al-Hashr"),
  ('الممتحنة', 13, false, "Al-Mumtahana"),
  ('الصف', 14, false, "As-Saff"),
  ('الجمعة', 11, false, "Al-Jumu'a"),
  ('المنافقون', 11, false, "Al-Munaafiqoon"),
  ('التغابن', 18, false, "At-Taghaabun"),
  ('الطلاق', 12, false, "At-Talaaq"),
  ('التحريم', 12, false, "At-Tahrim"),
  ('الملك', 30, true, "Al-Mulk"),
  ('القلم', 52, true, "Al-Qalam"),
  ('الحاقة', 52, true, "Al-Haaqqa"),
  ('المعارج', 44, true, "Al-Ma'aarij"),
  ('نوح', 28, true, "Nooh"),
  ('الجن', 28, true, "Al-Jinn"),
  ('المزمل', 20, true, "Al-Muzzammil"),
  ('المدثر', 56, true, "Al-Muddaththir"),
  ('القيامة', 40, true, "Al-Qiyaama"),
  ('الانسان', 31, false, "Al-Insaan"),
  ('المرسلات', 50, true, "Al-Mursalaat"),
  ('النبإ', 40, true, "An-Naba"),
  ('النازعات', 46, true, "An-Naazi'aat"),
  ('عبس', 42, true, "Abasa"),
  ('التكوير', 29, true, "At-Takwir"),
  ('الإنفطار', 19, true, "Al-Infitaar"),
  ('المطففين', 36, true, "Al-Mutaffifin"),
  ('الإنشقاق', 25, true, "Al-Inshiqaaq"),
  ('البروج', 22, true, "Al-Burooj"),
  ('الطارق', 17, true, "At-Taariq"),
  ('الأعلى', 19, true, "Al-A'laa"),
  ('الغاشية', 26, true, "Al-Ghaashiya"),
  ('الفجر', 30, true, "Al-Fajr"),
  ('البلد', 20, true, "Al-Balad"),
  ('الشمس', 15, true, "Ash-Shams"),
  ('الليل', 21, true, "Al-Lail"),
  ('الضحى', 11, true, "Ad-Dhuhaa"),
  ('الشرح', 8, true, "Ash-Sharh"),
  ('التين', 8, true, "At-Tin"),
  ('العلق', 19, true, "Al-Alaq"),
  ('القدر', 5, true, "Al-Qadr"),
  ('البينة', 8, false, "Al-Bayyina"),
  ('الزلزلة', 8, false, "Az-Zalzala"),
  ('العاديات', 11, true, "Al-Aadiyaat"),
  ('القارعة', 11, true, "Al-Qaari'a"),
  ('التكاثر', 8, true, "At-Takaathur"),
  ('العصر', 3, true, "Al-Asr"),
  ('الهمزة', 9, true, "Al-Humaza"),
  ('الفيل', 5, true, "Al-Fil"),
  ('قريش', 4, true, "Quraish"),
  ('الماعون', 7, true, "Al-Maa'un"),
  ('الكوثر', 3, true, "Al-Kawthar"),
  ('الكافرون', 6, true, "Al-Kaafiroon"),
  ('النصر', 3, false, "An-Nasr"),
  ('المسد', 5, true, "Al-Masad"),
  ('الإخلاص', 4, true, "Al-Ikhlaas"),
  ('الفلق', 5, true, "Al-Falaq"),
  ('الناس', 6, true, "An-Naas"),
];

/// First (surah, ayah) of each juz (1..30).
const juzStarts = <(int, int)>[
  (1, 1),
  (2, 142),
  (2, 253),
  (3, 93),
  (4, 24),
  (4, 148),
  (5, 82),
  (6, 111),
  (7, 88),
  (8, 41),
  (9, 93),
  (11, 6),
  (12, 53),
  (15, 1),
  (17, 1),
  (18, 75),
  (21, 1),
  (23, 1),
  (25, 21),
  (27, 56),
  (29, 46),
  (33, 31),
  (36, 28),
  (39, 32),
  (41, 47),
  (46, 1),
  (51, 31),
  (58, 1),
  (67, 1),
  (78, 1),
];

/// Ayahs of prostration (surah, ayah).
const sajdaAyahs = <(int, int)>{
  (7, 206),
  (13, 15),
  (16, 50),
  (17, 109),
  (19, 58),
  (22, 18),
  (22, 77),
  (25, 60),
  (27, 26),
  (32, 15),
  (38, 24),
  (41, 38),
  (53, 62),
  (84, 21),
  (96, 19),
};
